### ISSUE TITLE
"Keras requires Tensorflow 2.2 or higher" on fresh install of gutenhaiku

### ISSUE THREAD

**Issue by dlebech** [sloev/gutenhaiku#2]
Fun project @sloev !

I was looking to extract some rad Haiku, so I made a fresh conda environment with Python 3.7 and installed gutenhaiku according to the README. However, I ran into a problem while running the CLI:
```
ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`
```
I can't quite figure out a way to fix this error. Full stacktrace below:
```
  We start by doing some loading of fancy AI models..Traceback (most recent call last):
  File "/libs/miniconda3/envs/gutenhaiku/lib/python3.7/site-packages/keras/__init__.py", line 3, in <module>
    from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
ModuleNotFoundError: No module named 'tensorflow.keras.layers.experimental.preprocessing'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/libs/miniconda3/envs/gutenhaiku/bin/gutenhaiku", line 8, in <module>
    sys.exit(cli())
  File "/libs/miniconda3/envs/gutenhaiku/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/libs/miniconda3/envs/gutenhaiku/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/libs/miniconda3/envs/gutenhaiku/lib/python3.7/site-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/libs/miniconda3/envs/gutenhaiku/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/libs/miniconda3/envs/gutenhaiku/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/libs/miniconda3/envs/gutenhaiku/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/libs/miniconda3/envs/gutenhaiku/lib/python3.7/site-packages/gutenhaiku/app.py", line 180, in cli
    from gutenhaiku import pipeline
  File "/libs/miniconda3/envs/gutenhaiku/lib/python3.7/site-packages/gutenhaiku/pipeline.py", line 16, in <module>
    from deepcorrect import DeepCorrect
  File "/libs/miniconda3/envs/gutenhaiku/lib/python3.7/site-packages/deepcorrect/__init__.py", line 1, in <module>
    from .deepcorrect import DeepCorrect
  File "/libs/miniconda3/envs/gutenhaiku/lib/python3.7/site-packages/deepcorrect/deepcorrect.py", line 1, in <module>
    from txt2txt import build_model, infer
  File "/libs/miniconda3/envs/gutenhaiku/lib/python3.7/site-packages/txt2txt/__init__.py", line 3, in <module>
    from .txt2txt import *
  File "/libs/miniconda3/envs/gutenhaiku/lib/python3.7/site-packages/txt2txt/txt2txt.py", line 10, in <module>
    from keras.layers import Input, Embedding, LSTM, TimeDistributed, Dense, SimpleRNN, Activation, dot, concatenate, Bidirectional
  File "/libs/miniconda3/envs/gutenhaiku/lib/python3.7/site-packages/keras/__init__.py", line 6, in <module>
    'Keras requires TensorFlow 2.2 or higher. '
ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`
```

**Comment by sloev** [comment]
@dlebech this is a known issue of imcompatibility between keras and tensorflow version wise, i will check it out later today.

btw: really miss talking to you, hope i get a chance to hook up this year! 🤗
